services:
    _defaults:
        autowire: true
        autoconfigure: true

    SymfonyBundle\UIBundle\Command\:
        resource: '../../../src/*'
        exclude:
            - '../../../src/DependencyInjection/'

    SymfonyBundle\UIBundle\Command\Core\Service\ValidatorService:
        class: SymfonyBundle\UIBundle\Command\Core\Service\ValidatorService
        public: true
